feat: add metada to base strategy
iearn-finance/yearn-vaults pull request #169
Opened 2021-01-28 09:29 UTC by steffenix

closes #165

2021-01-28 23:23 UTC, fubuloubu approved these changes

2021-01-28 23:23 UTC, fubuloubu commented on contracts/BaseStrategy.sol
> +    constructor(address _vault, string memory _metadataURI) public {
Don't add it to the constructor

2021-01-28 23:24 UTC, fubuloubu requested changes

2021-01-28 23:24 UTC, fubuloubu commented on tests/functional/strategy/test_misc.py
> +    strategy.setMetadataURI("ipfs://test", {"from": gov})
```suggestion
    assert strategy.metadataURL() == ""  # Empty by default
    strategy.setMetadataURI("ipfs://test", {"from": gov})
    assert strategy.metadataURL() == "ipfs://test"
    strategy.setMetadataURI("ipfs://test2", {"from": gov})
    assert strategy.metadataURL() == "ipfs://test2"
```

2021-01-28 23:27 UTC, fubuloubu commented
Address above comments and good to merge!

2021-01-28 23:30 UTC, fubuloubu requested changes
nit: because this affects the event id

2021-01-28 23:30 UTC, fubuloubu commented on contracts/BaseStrategy.sol
> +    event UpdatedMetaDataUri(string metadataURI);
```suggestion
    event UpdatedMetadataURI(string metadataURI);
```

2021-01-28 23:30 UTC, fubuloubu commented on contracts/BaseStrategy.sol
> +        emit UpdatedMetaDataUri(_metadataURI);
```suggestion
        emit UpdatedMetadataURI(_metadataURI);
```

2021-01-29 07:34 UTC, fubuloubu approved these changes
Fix up your commit message if you can, so it passes commit lint

2021-01-29 07:34 UTC, fubuloubu commented on contracts/test/TestStrategy.sol
> +    constructor(address _vault) public BaseStrategy(_vault, "") {}
revert this change back

2021-01-29 07:40 UTC, steffenix commented
> Fix up your commit message if you can, so it passes commit lint

I did made a mistake with the suggested changes commit message. It's fixed.

2021-01-29 08:00 UTC, steffenix commented
ready

2021-01-29 15:55 UTC, dougstorm approved these changes

2021-01-29 18:00 UTC, merged